// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookup.Models;

namespace ParksLookup.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    partial class ParksLookupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ParkDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParkName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("StateName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            ParkDescription = "wilderness recreations area atop a volcanic hot spot",
                            ParkName = "Yellowstone National Park",
                            StateName = "Wyoming"
                        },
                        new
                        {
                            ParkId = 2,
                            ParkDescription = "Inside California's Sierra Nevada mountains",
                            ParkName = "Yosemite National Park",
                            StateName = "California"
                        },
                        new
                        {
                            ParkId = 3,
                            ParkDescription = "Popular summer destination for mountaineering, hiking, backcountry camping and fishing",
                            ParkName = "Grand Teton National Park",
                            StateName = "Wyoming"
                        },
                        new
                        {
                            ParkId = 4,
                            ParkDescription = "Wide views of canyons revealing layered bands of red rock",
                            ParkName = "Grand Canyon National Park",
                            StateName = "Arizona"
                        },
                        new
                        {
                            ParkId = 5,
                            ParkDescription = "Glacier carved peaks and valleys running to the Canadian border",
                            ParkName = "Glacier National Park",
                            StateName = "Montana"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
